# Generated by Django 5.0.6 on 2024-06-22 14:00

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=50, null=True)),
                ('lastName', models.CharField(blank=True, max_length=50, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('email_verified', models.BooleanField(blank=True, default=False, null=True, verbose_name='is email Verified')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('onboarding_done', models.BooleanField(blank=True, default=False, null=True, verbose_name='is onboarded')),
                ('profile_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
