# Generated by Django 5.0.6 on 2024-06-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_taskboard', '0003_alter_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
    ]
