# Generated by Django 5.0.6 on 2024-06-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_taskboard', '0004_remove_task_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name="task's Description"),
        ),
    ]
