# Generated by Django 5.0.6 on 2024-06-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_taskboard', '0011_alter_task_options_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='important',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
