# Generated by Django 5.0.6 on 2024-06-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_taskboard', '0012_task_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='important',
            field=models.CharField(choices=[('Yes', True), ('No', False)], default='No', max_length=10),
        ),
    ]
